export const BLOG_POSTS = [
  {
    slug: 'life-expectancy-factors',
    title: 'What Affects Your Life Expectancy?',
    excerpt: 'Smoking, exercise, sleep, and stress — how each one actually moves the number, based on WHO and CDC research.',
    category: 'guide',
    path: '/life-expectancy-factors',
  },
  {
    slug: 'blue-zones',
    title: 'Blue Zones: Where People Live the Longest',
    excerpt: 'Okinawa, Sardinia, Nicoya, Ikaria, and Loma Linda — the five regions where people routinely reach 90 and beyond.',
    category: 'guide',
    path: '/blue-zones',
  },
  {
    slug: 'life-in-weeks',
    title: 'Your Life in Weeks',
    excerpt: 'Why seeing your entire life as a grid of weeks changes decisions in a way a number on its own never does.',
    category: 'guide',
    path: '/life-in-weeks',
  },
  {
    slug: 'life-trivia',
    title: 'Life Trivia: Weird Numbers About a Human Lifetime',
    excerpt: 'Heartbeats, hours slept, time spent commuting and scrolling — fun, surprising numbers about a lifetime.',
    category: 'guide',
    path: '/life-trivia',
  },
  {
    slug: 'sleep-and-longevity',
    title: 'Sleep and Longevity: The Real Connection',
    excerpt: 'What the sleep-duration research actually says about how many years good or bad sleep adds or costs you.',
    category: 'guide',
    path: '/sleep-and-longevity',
    image: '/images/blog/sleep-duration-mortality-risk-chart.webp',
  },
  {
    slug: 'life-expectancy-india',
    title: 'Life Expectancy in India',
    excerpt: 'How India\'s life expectancy has changed since 1950, current causes of death, and the healthcare gap.',
    category: 'country',
    path: '/life-expectancy/india',
  },
  {
    slug: 'life-expectancy-usa',
    title: 'Life Expectancy in the USA',
    excerpt: 'Why the US trails other wealthy nations despite outspending all of them on healthcare.',
    category: 'country',
    path: '/life-expectancy/usa',
  },
  {
    slug: 'life-expectancy-russia',
    title: 'Life Expectancy in Russia',
    excerpt: 'The 10-year gender gap, alcohol policy, and the post-Soviet mortality crisis explained.',
    category: 'country',
    path: '/life-expectancy/russia',
  },
  {
    slug: 'life-expectancy-spain',
    title: 'Life Expectancy in Spain',
    excerpt: 'One of the highest life expectancies in the world — the diet, healthcare, and lifestyle reasons why.',
    category: 'country',
    path: '/life-expectancy/spain',
  },
  {
    slug: 'life-expectancy-japan',
    title: 'Life Expectancy in Japan',
    excerpt: 'Japan\'s aging population, its highest-in-the-world numbers, and what\'s actually behind them.',
    category: 'country',
    path: '/life-expectancy/japan',
    image: '/images/blog/japan-life-expectancy-2026-hero.webp',
  },
  {
  slug: 'monaco-life-expectancy',
  path: '/life-expectancy/monaco',
  title: "Monaco Life Expectancy — The World's Highest, and Why It's Complicated",
  excerpt: "Monaco tops every global ranking at ~86.4 years. Here's the honest breakdown of what's really behind the number.",
  category: 'country',
  image: '/images/blog/monaco-coastline-aerial.webp',
},
{
  slug: 'diet-patterns-and-longevity',
  path: '/diet-patterns-and-longevity',
  title: 'Mediterranean Diet vs Everything Else: What the Longevity Research Shows',
  excerpt: 'Mediterranean diet adherence cuts mortality risk by up to 36% — but ultra-processed food intake independently undercuts it.',
  category: 'guide',
  image: '/images/blog/mediterranean-diet-foods-flatlay.webp',
},
{
  slug: 'life-expectancy-uk',
  path: '/life-expectancy/uk',
  title: 'UK Life Expectancy 2026 — Record Highs and a Widening Health Gap',
  excerpt: "England's male life expectancy just crossed 80 for the first time — but the healthspan gap is the real story.",
  category: 'country',
  image: '/images/blog/uk-life-expectancy-2026-chart.webp',
},
{
  slug: 'cardio-vs-strength-training',
  path: '/cardio-vs-strength-training',
  title: 'Cardio vs Strength Training for Longevity: What the Research Shows',
  excerpt: 'Three decades of cohort data compared — and the honest answer to "cardio or weights" is neither one alone.',
  category: 'guide',
  image: '/images/blog/cardio-vs-strength-training-mortality-chart.webp',
},
{
  slug: 'life-expectancy-germany',
  path: '/life-expectancy/germany',
  title: 'Germany Life Expectancy 2026 — Official Data and the Smoking Problem Nobody Fixed',
  excerpt: "Germany trails most of Western Europe on life expectancy despite great healthcare — here's the state-by-state data and why.",
  category: 'country',
  image: '/images/blog/germany-life-expectancy-2026-hero.webp',
},
{
  slug: 'smoking-cessation-recovery',
  path: '/smoking-cessation-recovery',
  title: 'Smoking Cessation Timeline 2026: What Actually Happens to Your Body After You Quit',
  excerpt: 'From 20 minutes to 15 years — the real, data-backed recovery timeline after your last cigarette.',
  category: 'guide',
  image: '/images/blog/smoking-cessation-recovery-timeline-2026.webp',
}
]