export const LIFE_FACTS = [
  'In the time you have been reading this page, your heart has beaten over 600 times.',
  'You will spend 6 years of your life dreaming.',
  'The average person walks 100,000 miles in their lifetime — enough to circle the Earth 4 times.',
  'You share your birthday with roughly 22 million other people alive today.',
  'By the time you finish reading this sentence, 8 people will have died somewhere in the world.',
  'The cells in your body are replaced roughly every 7–10 years. You are literally not the same person you were a decade ago.',
  'You will forget 90% of what happened to you today by next week.',
  'The average human takes 550 million breaths in a lifetime.',
  'You have roughly 86,400 seconds today. You cannot save any for tomorrow.',
  'Every 60 seconds, 108 people die and 267 babies are born.',
  'The average person spends 2 years of their life on the phone.',
  'You blink approximately 15,000 times a day — mostly without noticing.',
  'A human heart beats over 100,000 times a day, 40 million times a year, and 3 billion times in a lifetime.',
  'You produce enough saliva in your lifetime to fill two swimming pools.',
  'By age 60, you will have slept about 20 years of your life.',
  'The average person makes about 35,000 decisions every day.',
  'Every 7 seconds, a baby is born somewhere on Earth.',
  'You will spend roughly 1 year of your life looking for lost items.',
  'The human brain can process information as fast as 120 meters per second.',
  'You are made of approximately 37 trillion cells, each one working silently to keep you alive.',
  'In your lifetime, your heart will pump enough blood to fill 3 supertankers.',
  'The average person laughs about 15 times a day — but children laugh up to 400 times.',
  'You will eat roughly 35 tons of food over your lifetime.',
  'If you lined up all your blood vessels, they would stretch 60,000 miles — enough to circle the Earth twice.',
  'Every breath you take contains molecules that were once breathed by Julius Caesar, Cleopatra, and Einstein.',
  'Your bones are constantly rebuilding — your entire skeleton is replaced roughly every 10 years.',
  'The average person spends 5 years of their life eating.',
  'In a lifetime, the average person walks the equivalent of 5 trips around the Earth.',
  'You will spend about 4 months of your life waiting at red lights.',
  'The odds of you being born — given the exact sperm, egg, and ancestral chain required — are roughly 1 in 400 trillion.',
]