export const QUOTES = [
  { text: 'The trouble is, you think you have time.', author: 'Jack Kornfield' },
  { text: 'We suffer more in imagination than in reality.', author: 'Seneca' },
  { text: 'It is not death that a man should fear, but he should fear never beginning to live.', author: 'Marcus Aurelius' },
  { text: 'Die with memories, not dreams.', author: 'Unknown' },
  { text: 'You could leave life right now. Let that determine what you do and say and think.', author: 'Marcus Aurelius' },
  { text: 'He who is not everyday conquering some fear has not learned the secret of life.', author: 'Ralph Waldo Emerson' },
  { text: 'The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.', author: 'Mark Twain' },
  { text: 'I have lived with the prospect of an early death for the last 49 years. I\'m not afraid of death, but I\'m in no hurry to die.', author: 'Stephen Hawking' },
  { text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard' },
  { text: 'Time flies over us, but leaves its shadow behind.', author: 'Nathaniel Hawthorne' },
  { text: 'Do not act as if you had ten thousand years to live.', author: 'Marcus Aurelius' },
  { text: 'The present moment always will have been.', author: 'Seneca' },
  { text: 'Waste no more time arguing about what a good man should be. Be one.', author: 'Marcus Aurelius' },
  { text: 'It is not that we have a short time to live, but that we waste a good deal of it.', author: 'Seneca' },
  { text: 'Our life is frittered away by detail. Simplify, simplify.', author: 'Henry David Thoreau' },
  { text: 'The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.', author: 'Ralph Waldo Emerson' },
  { text: 'Perfection of character is this: to live each day as if it were your last, without frenzy, without apathy, without pretense.', author: 'Marcus Aurelius' },
  { text: 'Begin at once to live, and count each separate day as a separate life.', author: 'Seneca' },
  { text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius' },
  { text: 'He suffers more than necessary, who suffers before it is necessary.', author: 'Seneca' },
  { text: 'The best revenge is not to be like your enemy.', author: 'Marcus Aurelius' },
  { text: 'A man is not old until regrets take the place of dreams.', author: 'John Barrymore' },
  { text: 'One day you will be at the place you always wanted to be. Don\'t stop believing.', author: 'Lin Yutang' },
  { text: 'Life is what happens when you\'re busy making other plans.', author: 'John Lennon' },
  { text: 'Tell me, what is it you plan to do with your one wild and precious life?', author: 'Mary Oliver' },
  { text: 'Be yourself; everyone else is already taken.', author: 'Oscar Wilde' },
  { text: 'In three words I can sum up everything I\'ve learned about life: it goes on.', author: 'Robert Frost' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'Life is either a daring adventure or nothing at all.', author: 'Helen Keller' },
]