export const WORLD_EVENTS = [
  { year: 1969, event: 'First humans walked on the Moon', category: 'science' },
  { year: 1989, event: 'Fall of the Berlin Wall', category: 'history' },
  { year: 1991, event: 'World Wide Web went public', category: 'tech' },
  { year: 1997, event: 'Harry Potter published', category: 'culture' },
  { year: 2001, event: 'September 11 attacks', category: 'history' },
  { year: 2004, event: 'Facebook launched', category: 'tech' },
  { year: 2005, event: 'YouTube launched', category: 'tech' },
  { year: 2007, event: 'iPhone launched', category: 'tech' },
  { year: 2008, event: 'Global financial crisis', category: 'history' },
  { year: 2009, event: 'Bitcoin invented', category: 'tech' },
  { year: 2010, event: 'iPad launched', category: 'tech' },
  { year: 2012, event: 'Instagram hit 100M users', category: 'culture' },
  { year: 2016, event: 'India Demonetization', category: 'india' },
  { year: 2016, event: 'Pokemon Go went viral', category: 'culture' },
  { year: 2019, event: 'India wins ICC World Test Championship', category: 'india' },
  { year: 2020, event: 'COVID-19 global pandemic began', category: 'history' },
  { year: 2022, event: 'ChatGPT launched, AI era began', category: 'tech' },
  { year: 2023, event: 'India lands on Moon (Chandrayaan-3)', category: 'india' },
  { year: 2024, event: 'India wins T20 World Cup', category: 'india' },
  { year: 2024, event: 'Gemini, GPT-4o, Claude 3.5 released', category: 'tech' },
  { year: 2025, event: 'AI agents began replacing white-collar jobs', category: 'tech' },
  { year: 2026, event: 'FIFA World Cup 2026 (USA/Canada/Mexico)', category: 'culture' },
]